"""Presqu'île manual sanity validation points."""

from __future__ import annotations

from typing import Any

# Observed classes are screening judgments for wind from wind_direction_deg.
PRESQUILE_SANITY_SAMPLES: list[dict[str, Any]] = [
    {
        "name": "Pont Lafayette (E-W wind)",
        "lon": 4.8412, "lat": 45.7662,
        "feature_types": ["bridge"],
        "observed_class": "high",
        "wind_direction_deg": 90,
        "notes": "Bridge deck crosswind exposure",
    },
    {
        "name": "Quai du Rhône (along-river)",
        "lon": 4.8405, "lat": 45.7555,
        "feature_types": ["quay", "street_segment"],
        "observed_class": "medium",
        "wind_direction_deg": 180,
        "notes": "River-aligned fetch",
    },
    {
        "name": "Place Bellecour (open)",
        "lon": 4.8320, "lat": 45.7578,
        "feature_types": ["open_space", "street_segment"],
        "observed_class": "medium",
        "wind_direction_deg": 270,
        "notes": "Large open square",
    },
    {
        "name": "Rue de la République (canyon N-S)",
        "lon": 4.8360, "lat": 45.7620,
        "feature_types": ["street_segment"],
        "observed_class": "high",
        "wind_direction_deg": 0,
        "notes": "Aligned canyon channeling",
    },
    {
        "name": "Rue Victor Hugo (perpendicular)",
        "lon": 4.8385, "lat": 45.7595,
        "feature_types": ["street_segment"],
        "observed_class": "low",
        "wind_direction_deg": 90,
        "notes": "Cross-wind to N-S corridor",
    },
    {
        "name": "Saône quay Vieux Lyon",
        "lon": 4.8285, "lat": 45.7625,
        "feature_types": ["quay", "street_segment"],
        "observed_class": "medium",
        "wind_direction_deg": 45,
        "notes": "River edge gust potential",
    },
    {
        "name": "Opera - deep street",
        "lon": 4.8372, "lat": 45.7588,
        "feature_types": ["street_segment"],
        "observed_class": "high",
        "wind_direction_deg": 180,
        "notes": "Narrow canyon aligned with wind",
    },
    {
        "name": "Terreaux square",
        "lon": 4.8335, "lat": 45.7670,
        "feature_types": ["open_space"],
        "observed_class": "medium",
        "wind_direction_deg": 225,
        "notes": "Open civic space",
    },
    {
        "name": "Part-Dieu approach (wide)",
        "lon": 4.8420, "lat": 45.7605,
        "feature_types": ["street_segment"],
        "observed_class": "low",
        "wind_direction_deg": 90,
        "notes": "Wide modern grid crosswind",
    },
    {
        "name": "Rhône park edge",
        "lon": 4.8418, "lat": 45.7680,
        "feature_types": ["park", "vegetation"],
        "observed_class": "low",
        "wind_direction_deg": 270,
        "notes": "Vegetation shelter",
    },
    {
        "name": "Tunnel approach (excluded)",
        "lon": 4.8348, "lat": 45.7548,
        "feature_types": ["tunnel", "underpass"],
        "observed_class": "low",
        "wind_direction_deg": 90,
        "notes": "Interior not modeled — expect low/excluded",
    },
    {
        "name": "Jacobins square",
        "lon": 4.8368, "lat": 45.7608,
        "feature_types": ["open_space"],
        "observed_class": "medium",
        "wind_direction_deg": 0,
        "notes": "Partial enclosure by buildings",
    },
    {
        "name": "Cordeliers narrow street",
        "lon": 4.8350, "lat": 45.7635,
        "feature_types": ["street_segment"],
        "observed_class": "high",
        "wind_direction_deg": 0,
        "notes": "Old fabric narrow canyon",
    },
    {
        "name": "Hotel-Dieu river front",
        "lon": 4.8298, "lat": 45.7598,
        "feature_types": ["quay", "building"],
        "observed_class": "medium",
        "wind_direction_deg": 135,
        "notes": "Saône river front",
    },
    {
        "name": "Bourse wide intersection",
        "lon": 4.8378, "lat": 45.7645,
        "feature_types": ["street_segment", "open_space"],
        "observed_class": "medium",
        "wind_direction_deg": 45,
        "notes": "Corner acceleration zone",
    },
]